name: logger
description: Logger package
publish_to: none
version: 0.0.1

resolution: workspace

workspace:
  - packages/talker_flutter

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  sentry_dio: ^9.6.0
  sentry_flutter: ^9.6.0
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  freezed_annotation: ^3.1.0
  talker_dio_logger: ^5.0.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  go_router: ^14.6.2
  talker_flutter:
    path: packages/talker_flutter

dev_dependencies:
  freezed: ^3.2.3
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  dependency_validator: ^5.0.2

flutter:
  generate: true
